version: 0.2

phases:
        install:
                runtime-versions:
                        java: corretto11
        pre_build:
                commands:
                        - echo pre_buile...
                        - sudo apt-get update && sudo apt-get install -y maven
        build:
                commands:
                        - echo build...
                        - mvn install
        post_build:
                commands:
                        - echo post_build...
artifacts:
        files:
                - appspec.yml
                - target/testapp-0.1.war
		- scripts/before-install.sh
        discard-paths: yes
