version: 0.2

phases:
        install:
                runtime-versions:
                        java: corretto11
        pre_build:
                commands:
                        - echo pre_buile...
                        - sudo apt-get update && sudo apt-get install -y maven
                        - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 100450219031.dkr.ecr.ap-northeast-2.amazonaws.com
        build:
                commands:
                        - echo build...
                        - mvn install
                        - docker build -t testapp .
                        - docker tag testapp 100450219031.dkr.ecr.ap-northeast-2.amazonaws.com/testapp
        post_build:
                commands:
                        - echo post_build...
                        - docker push 100450219031.dkr.ecr.ap-northeast-2.amazonaws.com/testapp
                        - printf '[{"name":"test-container", "imageUri":"%s"}]' 100450219031.dkr.ecr.ap-northeast-2.amazonaws.com/testapp:latest > imageDetail.json
artifacts:
        files:
                - appspec.yml
                - imageDetail.json
                - taskdef.json
